utf8: Specify [[fallthrough]] attribute
g++ 7.3.0 warns about implicit fallthrough:

src/utf8.cc: In function ‘int next_state(int, unsigned char)’:
src/utf8.cc:25:19: error: this statement may fall through [-Werror=implicit-fallthrough=]
 case (s * 4) + 0: if (r0) return 0;                            \
                   ^
src/utf8.cc:45:33: note: in expansion of macro ‘SEQ1_HELPER’
 #define SEQ1(s, r0)             SEQ1_HELPER(s, r0)
                                 ^~~~~~~~~~~
src/utf8.cc:76:2: note: in expansion of macro ‘SEQ1’
  SEQ1(0, EGNAR(0x00, 0x7F))
  ^~~~
src/utf8.cc:28:1: note: here
 case (s * 4) + 0: if (r0) return (s * 4) + 1; goto SEQ_END(s); \
 ^
src/utf8.cc:46:33: note: in expansion of macro ‘SEQ2_HELPER’
 #define SEQ2(s, r0, r1)         SEQ2_HELPER(s, r0, r1)
                                 ^~~~~~~~~~~
src/utf8.cc:77:2: note: in expansion of macro ‘SEQ2’
  SEQ2(1, RANGE(0xC2, 0xDF), TAIL)
  ^~~~
cc1plus: all warnings being treated as errors
Makefile:49: recipe for target 'src/utf8.o' failed
make: *** [src/utf8.o] Error 1

Fixing it by providing the [[fallthrough]] attribute assuming that
the code is correct.

This silence the warning even though the attribute is actually C++17
and the Makefile is requesting to compile for C++11.